export const SUPABASE_URL = 'https://kybenuowpsbpozixatsc.supabase.co'
export const ANNON_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5YmVudW93cHNicG96aXhhdHNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA3NzUzNTcsImV4cCI6MjA0NjM1MTM1N30.VLQRxktUooq5tstDSyhP0tVPdTD3E0CEB4XcylNciSI';
